NATAR_HEROES_P1 = {
    "pudge": {
        "id": "pudge",
        "name": "Потрошитель (Мясник)",
        "icon": "🪝",
        "avatar": "🥩",
        "attr": "Сила",
        "desc": "Громила с гигантским тесаком и цепью. Неудержимое здоровье и регенерация плоти.",
        "base_hp": 220,
        "base_mp": 60,
        "str": 22,
        "agi": 9,
        "int": 8,
        "starter_weapon": {
            "uid": "w_starter_pudge",
            "name": "Ржавый Крюк",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🪝",
            "min_atk": 16,
            "max_atk": 24,
            "upgrade": 0,
            "bonus": {"str": 4},
            "bonus_desc": "⚔️ +16..24 Урон | 🥩 +4 Сила"
        },
        "starter_armor": {
            "uid": "a_starter_pudge",
            "name": "Фартук Мясника",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🦺",
            "defense": 8,
            "hp_bonus": 60,
            "upgrade": 0,
            "bonus": {"hp_regen": 4},
            "bonus_desc": "🛡️ +8 Броня | ❤️ +60 HP | 🩹 +4 HP/сек"
        },
        "skill": {
            "name": "Мясной Крюк & Пожирание",
            "icon": "🥩",
            "mp_cost": 25,
            "desc": "Хукает врага цепью, наносит 220% урона и восстанавливает себе 50 HP!"
        }
    },
    "juggernaut": {
        "id": "juggernaut",
        "name": "Мастер Клинка (Самурай)",
        "icon": "🗡️",
        "avatar": "👺",
        "attr": "Ловкость",
        "desc": "Непревзойденный фехтовальщик бури. Шквал смертоносных ударов и ураганная скорость атаки.",
        "base_hp": 150,
        "base_mp": 70,
        "str": 13,
        "agi": 21,
        "int": 9,
        "starter_weapon": {
            "uid": "w_starter_jug",
            "name": "Катана Бури",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🗡️",
            "min_atk": 18,
            "max_atk": 26,
            "upgrade": 0,
            "bonus": {"crit": 15},
            "bonus_desc": "⚔️ +18..26 Урон | 💥 +15% Крит"
        },
        "starter_armor": {
            "uid": "a_starter_jug",
            "name": "Маска Предков",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🎭",
            "defense": 7,
            "hp_bonus": 30,
            "upgrade": 0,
            "bonus": {"dodge": 10},
            "bonus_desc": "🛡️ +7 Броня | ❤️ +30 HP | 💨 +10% Уворот"
        },
        "skill": {
            "name": "Танец Клинков (Шквал)",
            "icon": "⚡",
            "mp_cost": 25,
            "desc": "Серия из 3 молниеносных рассекающих ударов (по 130% урона с гарантированным критом)!"
        }
    },
    "phantom_assassin": {
        "id": "phantom_assassin",
        "name": "Теневой Клинок (Убийца)",
        "icon": "🩸",
        "avatar": "🥷",
        "attr": "Ловкость",
        "desc": "Бесшумная тень ночи. Мастер уклонения от ударов и сокрушительных смертельных выпадов.",
        "base_hp": 135,
        "base_mp": 65,
        "str": 11,
        "agi": 23,
        "int": 8,
        "starter_weapon": {
            "uid": "w_starter_pa",
            "name": "Кинжал Тени",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🗡️",
            "min_atk": 17,
            "max_atk": 25,
            "upgrade": 0,
            "bonus": {"crit": 20},
            "bonus_desc": "⚔️ +17..25 Урон | 💥 +20% Крит"
        },
        "starter_armor": {
            "uid": "a_starter_pa",
            "name": "Плащ Размытия",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🥋",
            "defense": 6,
            "hp_bonus": 25,
            "upgrade": 0,
            "bonus": {"dodge": 20},
            "bonus_desc": "🛡️ +6 Броня | ❤️ +25 HP | 💨 +20% Уворот"
        },
        "skill": {
            "name": "Смертельный Выпад",
            "icon": "💥",
            "mp_cost": 20,
            "desc": "Сокрушительный выпад из тени с шансом 400% критического урона!"
        }
    },
    "shadow_fiend": {
        "id": "shadow_fiend",
        "name": "Жнец Душ (Владыка Теней)",
        "icon": "💀",
        "avatar": "🖤",
        "attr": "Интеллект",
        "desc": "Повелевает украденными душами поверженных врагов. Испепеляющие темные взрывы и шторм душ.",
        "base_hp": 130,
        "base_mp": 95,
        "str": 10,
        "agi": 18,
        "int": 18,
        "starter_weapon": {
            "uid": "w_starter_sf",
            "name": "Осколок Тьмы",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🔥",
            "min_atk": 18,
            "max_atk": 27,
            "upgrade": 0,
            "bonus": {"mp": 25},
            "bonus_desc": "⚔️ +18..27 Урон | 🔮 +25 Мана"
        },
        "starter_armor": {
            "uid": "a_starter_sf",
            "name": "Мантия Теней",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🦹",
            "defense": 5,
            "hp_bonus": 25,
            "upgrade": 0,
            "bonus": {"mp_regen": 5},
            "bonus_desc": "🛡️ +5 Броня | ❤️ +25 HP | 🔮 +5 MP/сек"
        },
        "skill": {
            "name": "Взрыв Душ (Тройной Удар)",
            "icon": "🌑",
            "mp_cost": 25,
            "desc": "Три мощных взрыва темной энергии вокруг: суммарно 280% магического урона!"
        }
    },
}
