NATAR_HEROES_P2 = {
    "invoker": {
        "id": "invoker",
        "name": "Архимаг Стихий (Чародей)",
        "icon": "🔮",
        "avatar": "🧙‍♂️",
        "attr": "Интеллект",
        "desc": "Верховный магистр древних стихий. Огромный запас маны, метеоритные штормы и лучи солнца.",
        "base_hp": 125,
        "base_mp": 140,
        "str": 9,
        "agi": 10,
        "int": 25,
        "starter_weapon": {
            "uid": "w_starter_inv",
            "name": "Сфера Трех Стихий",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🔮",
            "min_atk": 17,
            "max_atk": 28,
            "upgrade": 0,
            "bonus": {"mp": 40},
            "bonus_desc": "⚔️ +17..28 Урон | 🔮 +40 Мана"
        },
        "starter_armor": {
            "uid": "a_starter_inv",
            "name": "Мантия Архимага",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "👘",
            "defense": 5,
            "hp_bonus": 25,
            "upgrade": 0,
            "bonus": {"int": 6},
            "bonus_desc": "🛡️ +5 Броня | ❤️ +25 HP | 🧙 +6 Интеллект"
        },
        "skill": {
            "name": "Санстрайк & Хаос Метеор",
            "icon": "☄️",
            "mp_cost": 30,
            "desc": "Солнечный луч Санстрайка с неба и пылающая «котлета» Хаос Метеора через всю арену!"
        }
    },
    "wraith_king": {
        "id": "wraith_king",
        "name": "Король Скелетов (Монарх)",
        "icon": "👑",
        "avatar": "💀",
        "attr": "Сила",
        "desc": "Древний бессмертный монарх катакомб. Сокрушительный вампиризм и несокрушимая стойкость.",
        "base_hp": 210,
        "base_mp": 55,
        "str": 21,
        "agi": 9,
        "int": 7,
        "starter_weapon": {
            "uid": "w_starter_wk",
            "name": "Меч Призрачного Монарха",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🗡️",
            "min_atk": 16,
            "max_atk": 24,
            "upgrade": 0,
            "bonus": {"lifesteal": 12},
            "bonus_desc": "⚔️ +16..24 Урон | 🩸 +12% Вампиризм"
        },
        "starter_armor": {
            "uid": "a_starter_wk",
            "name": "Корона Костяного Царя",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "👑",
            "defense": 9,
            "hp_bonus": 50,
            "upgrade": 0,
            "bonus": {"hp": 30},
            "bonus_desc": "🛡️ +9 Броня | ❤️ +80 HP"
        },
        "skill": {
            "name": "Призрачный Стан & Крит",
            "icon": "💥",
            "mp_cost": 20,
            "desc": "Оглушает врага снарядом призраков и наносит 250% урона с вампиризмом!"
        }
    },
    "anti_mage": {
        "id": "anti_mage",
        "name": "Охотник на Магов (Каратель)",
        "icon": "⚔️",
        "avatar": "🧑‍🦲",
        "attr": "Ловкость",
        "desc": "Быстрый охотник на чародеев. Рассекает эфир, выжигает ману врагов и взрывает боссов.",
        "base_hp": 145,
        "base_mp": 60,
        "str": 13,
        "agi": 22,
        "int": 6,
        "starter_weapon": {
            "uid": "w_starter_am",
            "name": "Парные Клинки Охотника",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "⚔️",
            "min_atk": 17,
            "max_atk": 25,
            "upgrade": 0,
            "bonus": {"mana_burn": 15},
            "bonus_desc": "⚔️ +17..25 Урон | ⚡ Сжигание маны"
        },
        "starter_armor": {
            "uid": "a_starter_am",
            "name": "Одеяния Монаха",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🥋",
            "defense": 7,
            "hp_bonus": 30,
            "upgrade": 0,
            "bonus": {"magic_resist": 25},
            "bonus_desc": "🛡️ +7 Броня | ❤️ +30 HP | 🔮 +25% Сопр. магии"
        },
        "skill": {
            "name": "Взрыв Пустоты (Кара)",
            "icon": "⚡",
            "mp_cost": 20,
            "desc": "Выжигает запасы маны врага и взрывает его изнутри на 260% урона!"
        }
    }
}
