# Package backend.db.crud
# Re-exports all CRUD functions for 100% backwards compatibility.

from backend.db.crud.users import (
    get_user_by_tg_id,
    create_user,
    update_user_role,
    update_user_name_and_role,
    update_user_custom_name,
    update_user_tester_status,
    get_pending_users,
    get_active_users,
    get_notifiable_users,
    toggle_user_notifications,
    get_all_users,
    delete_user,
    get_group_chat_by_id,
    create_or_update_group_chat,
    update_group_chat_role,
    get_approved_group_chats,
    get_pending_group_chats,
    update_group_chat_topic,
)

from backend.db.crud.subjects import (
    get_all_subjects,
    get_subject_by_id,
    get_subject_by_name,
    create_subject,
    get_or_create_subject,
    delete_subject,
)

from backend.db.crud.bells import (
    recalculate_bell_schedule_chain,
    set_bell_break_duration,
    get_bell_schedule,
    get_bell_schedule_for_date,
    set_bell_schedule_item,
    clear_date_bells,
    save_bulk_date_bells,
)

from backend.db.crud.schedule import (
    get_permanent_schedule_for_day,
    get_schedule_for_day,
    get_schedule_for_date,
    get_full_week_schedule,
    set_schedule_item,
    freeze_past_schedules_for_weekday,
    set_permanent_schedule_item,
    set_date_schedule_item,
    delete_date_schedule_item,
    clear_date_schedule,
    clear_permanent_day_schedule,
    save_bulk_date_schedule,
    save_bulk_permanent_schedule,
    get_substitutions_for_date,
    create_substitution,
)

from backend.db.crud.homework import (
    create_homework,
    get_homework_for_date,
    get_homework_by_subject,
    get_homework_by_id,
    get_user_homework_status,
    toggle_homework_completion,
    cleanup_past_homework_statuses,
    delete_homework,
    get_recent_active_homeworks,
    get_all_upcoming_homeworks,
    get_upcoming_deadlines,
    create_deadline,
    delete_deadline,
    create_announcement,
    get_recent_announcements,
    is_subject_scheduled_on_date,
    find_upcoming_dates_for_subject,
    auto_shift_active_homeworks,
)

from backend.db.crud.duty import (
    get_all_duty_groups,
    get_duty_group_by_number,
    create_or_update_duty_group,
    get_class_setting,
    set_class_setting,
    get_current_duty_info,
    clear_all_duty_members,
    get_users_in_duty_group,
)

__all__ = [
    # users & group chats
    "get_user_by_tg_id",
    "create_user",
    "update_user_role",
    "update_user_name_and_role",
    "update_user_custom_name",
    "update_user_tester_status",
    "get_pending_users",
    "get_active_users",
    "get_notifiable_users",
    "toggle_user_notifications",
    "get_all_users",
    "delete_user",
    "get_group_chat_by_id",
    "create_or_update_group_chat",
    "update_group_chat_role",
    "get_approved_group_chats",
    "get_pending_group_chats",
    "update_group_chat_topic",
    # subjects
    "get_all_subjects",
    "get_subject_by_id",
    "get_subject_by_name",
    "create_subject",
    "get_or_create_subject",
    "delete_subject",
    # bells
    "recalculate_bell_schedule_chain",
    "set_bell_break_duration",
    "get_bell_schedule",
    "get_bell_schedule_for_date",
    "set_bell_schedule_item",
    "clear_date_bells",
    "save_bulk_date_bells",
    # schedule
    "get_permanent_schedule_for_day",
    "get_schedule_for_day",
    "get_schedule_for_date",
    "get_full_week_schedule",
    "set_schedule_item",
    "freeze_past_schedules_for_weekday",
    "set_permanent_schedule_item",
    "set_date_schedule_item",
    "delete_date_schedule_item",
    "clear_date_schedule",
    "clear_permanent_day_schedule",
    "save_bulk_date_schedule",
    "save_bulk_permanent_schedule",
    "get_substitutions_for_date",
    "create_substitution",
    # homework
    "create_homework",
    "get_homework_for_date",
    "get_homework_by_subject",
    "get_homework_by_id",
    "get_user_homework_status",
    "toggle_homework_completion",
    "cleanup_past_homework_statuses",
    "delete_homework",
    "get_recent_active_homeworks",
    "get_all_upcoming_homeworks",
    "get_upcoming_deadlines",
    "create_deadline",
    "delete_deadline",
    "create_announcement",
    "get_recent_announcements",
    "is_subject_scheduled_on_date",
    "find_upcoming_dates_for_subject",
    "auto_shift_active_homeworks",
    # duty
    "get_all_duty_groups",
    "get_duty_group_by_number",
    "create_or_update_duty_group",
    "get_class_setting",
    "set_class_setting",
    "get_current_duty_info",
    "clear_all_duty_members",
    "get_users_in_duty_group",
]
